version: '2'

services:

  frontend:
    build: ./frontend-vuejs
    expose:
      - '80'

  data:
    build: ./data
    expose:
      - '8080'

  reverse-proxy:
    build: ./reverse-proxy
    ports:
      # Enable web forwarding and map our reverse proxy to port 80
      - '80:80'  # HOST:CONTAINER
    depends_on:
      - node-exporter

  node-exporter:
    image: rycus86/prometheus-node-exporter:0.15.2-armhf
    expose:
      - '9100'
    command:
      # Disable some collectors to save up on bandwidth usage
      # The default collectors send 100 KB of data
      # Reference: https://github.com/prometheus/node_exporter
      - '--no-collector.diskstats'  # saves 9 KB => 91 KB payload
      - '--no-collector.netstat'    # saves 45 KB => 46 KB payload
      - '--no-collector.vmstat'     # saves 14 KB => 32 KB payload

  timelapse:
    build: ./timelapse
    privileged: true  # allow direct access to hardware resources
    labels:
      io.resin.features.kernel-modules: '1'	# bind mounts the host OS /lib/modules into the container. (i.e. /lib/modules:/lib/modules)
