version: '2'

services:

  frontend:
    build:
      context: ./frontend-vuejs
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    volumes:
      - ./frontend-vuejs:/usr/src/app:rw
      # The volume is effectively hiding node_modules from the host and must be in this order
      - node_modules:/usr/src/app/node_modules

  rabbitmq:
    image: rabbitmq:3.7-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
      RABBITMQ_ERLANG_COOKIE: 'SWQOKODSQALRPCLNMEQG'
      RABBITMQ_DEFAULT_VHOST: '/'
    ports:
      - '15672:15672'  # management UI
      - '5672:5672'    # default listening port

volumes:

  node_modules:
