version: '2'

services:

  ros-master:
    image: ros:melodic-ros-base
    command:
      - roscore

  ros-talker:
    build: ./ros-tutorials
    environment:
      - ROS_HOSTNAME=ros-talker
      - ROS_MASTER_URI=http://ros-master:11311
    # rosrun <package> <executable>
    command: rosrun roscpp_tutorials talker

  ros-listener:
    build: ./ros-tutorials
    environment:
      - ROS_HOSTNAME=ros-listener
      - ROS_MASTER_URI=http://ros-master:11311
    # rosrun <package> <executable>
    command: rosrun roscpp_tutorials listener

  ros-joy:
    build: ./ros-joy
    # Unlike single container applications, multicontainer applications
    # do not run containers in privileged mode by default. If you want
    # to make use of hardware, you will either have to set some services
    # to privileged, using `privileged: true`, or use the `cap_add` and
    # `devices` settings to map in the correct hardware access to the
    # container.
    privileged: true
    # devices:
    #   - '/dev/input/js0:/dev/input/js0'
    # cap_add:
    #   - SYS_RAWIO
    environment:
      - ROS_HOSTNAME=ros-joy
      - ROS_MASTER_URI=http://ros-master:11311
    command: rosparam set joy_node/dev "/dev/input/js0" && rosrun joy joy_node
